# Podfile for SpecKitRN React Native app
# iOS native module integration with KMP SDK

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/react-native/scripts/react_native_pods'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

target 'SpecKitRN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  # KMP SDK dependency
  pod 'shared', :path => '../../wellness-kmp-sdk/shared'

  target 'SpecKitRNTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
